services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clinic_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: clinic_db
    environment:
      MYSQL_DATABASE: clinic
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "3030:80"
    environment:
      - PMA_ARBITRARY=1

  webserver:
    image: nginx:alpine
    container_name: clinic_nginx
    ports:
      - "3000:80"
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
